name: atsign_location_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  sliding_up_panel: ^1.0.2
  map: ^0.2.0+1
  cached_network_image: ^2.3.3
  flutter_slidable: ^0.5.7
  flutter_qr_reader: ^1.0.3
  file_picker: ^2.0.7
  archive: ^2.0.13
  permission_handler: ^5.0.1+1
  qr_flutter: ^3.2.0
  share: ^0.6.5+2
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  latlong: ^0.6.1

  tuple: ^1.0.2
  positioned_tap_detector: ^1.0.2
  transparent_image: ^1.0.0
  async: ^2.1.0
  flutter_image: ^3.0.0
  path_provider: ^1.6.7
  vector_math: ^2.0.0
  proj4dart: ^1.0.4
  meta: ^1.1.0
  geolocator: ^6.2.1
  at_onboarding_flutter: ^1.0.0+1
  fluttertoast: ^8.0.3

  
  at_client_mobile: ^1.0.0+3
  at_contact: ^1.0.0
  at_commons: ^1.0.1+3
  at_lookup: ^1.0.0+3
  at_contacts_group_flutter:
    path: /Users/nitesh/Desktop/new_atsign/at_widgets/at_contacts_group_flutter
  at_contacts_flutter:
    path: /Users/nitesh/Desktop/new_atsign/at_widgets/at_contacts_flutter
  atsign_authentication_helper :
    path: /Users/nitesh/Desktop/new_atsign/at_widgets/atsign_authentication_helper
  at_chat_flutter:
    path: /Users/nitesh/Desktop/new_atsign/at_widgets/at_chat_flutter
  # atsign_authentication_helper :
  #   path: /Users/sachinsingh/Documents/geekyAnts/AtSign/at_widgets/atsign_authentication_helper



dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/person1.png
    - assets/images/person2.png
    - assets/images/splash_bg.png
    - assets/images/empty_group.png
    - assets/images/group_photo.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: HelveticaNeu
      fonts:
        - asset: assets/fonts/HelveticaLight.ttf
          weight: 300
        - asset: assets/fonts/HelveticaMedium.ttf
          weight: 500
        - asset: assets/fonts/HelveticaRegular.ttf
          weight: 400
        - asset: assets/fonts/HelveticaBold.otf
          weight: 700
        - asset: assets/fonts/HelveticaExtraBold.ttf
          weight: 800
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Bold.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
